update workflows

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -20,16 +20,16 @@ jobs:
 
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3  # เช็คเอาท์ repository ปัจจุบัน
+        uses: actions/checkout@v3
 
       - name: Install cosign
         if: github.event_name != 'pull_request'
         uses: sigstore/cosign-installer@v3.1.1
         with:
-          cosign-release: 'v2.1.1'  # ติดตั้ง cosign เวอร์ชัน 2.1.1
+          cosign-release: 'v2.1.1'
 
       - name: Setup Docker buildx
-        uses: docker/setup-buildx-action@v2  # ตั้งค่า Docker buildx
+        uses: docker/setup-buildx-action@v2
 
       - name: Log into registry
         if: github.event_name != 'pull_request'
@@ -37,7 +37,7 @@ jobs:
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}  # ล็อกอินเข้าสู่ Docker registry
+          password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set lowercase image name
         id: set_image_name
@@ -47,6 +47,10 @@ jobs:
         id: get-tag
         run: |
           TAG=$(echo "${GITHUB_REF#refs/tags/}")
+          if [ -z "$TAG" ]; then
+            echo "Error: No release tag found. Exiting."
+            exit 1
+          fi
           echo "TAG=${TAG}" >> $GITHUB_ENV
 
       - name: Build and push Docker image
@@ -55,6 +59,7 @@ jobs:
           context: .
           push: true
           tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
+
       - name: Set full image tag
         id: set_full_image_tag
         run: |
@@ -64,7 +69,6 @@ jobs:
         env:
           GITHUB_SHA: ${{ github.sha }}
 
-
   deploy:
     needs: build
     runs-on: ubuntu-20.04
@@ -73,14 +77,14 @@ jobs:
       - name: Setup Git
         run: |
           git config --global user.name "Github Actions"
-          git config --global user.email "actions@github.com"  # ตั้งค่า Git
+          git config --global user.email "actions@github.com"
 
       - name: Checkout gitops repository
         uses: actions/checkout@v3
         with:
           repository: Adapter877/sci-borrow
           ref: main
-          token: ${{ secrets.GH_PAT }}  # เช็คเอาท์ repository สำหรับ gitops
+          token: ${{ secrets.GH_PAT }}
 
       - name: Update image tag for UAT
         if: ${{ contains(github.event.release.tag_name, '-beta') }}
@@ -91,7 +95,7 @@ jobs:
           yq eval ".spec.template.spec.containers[0].image = \"$FULL_IMAGE_TAG\"" -i deployment/deployment.yaml
           git add deployment/deployment.yaml
           git commit -m "Set 'web' image tag to '${FULL_IMAGE_TAG}'"
-          git push  # อัปเดต image tag ในไฟล์ deployment สำหรับ UAT
+          git push
 
       - name: Check deployment file content
-        run: cat deployment/deployment.yaml  # ตรวจสอบเนื้อหาของไฟล์ deployment หลังจากอัปเดต
+        run: cat deployment/deployment.yaml
